### ISSUE TITLE
build.py script does not function properly on Windows 10 or Ubuntu 16.04

### ISSUE THREAD

**Issue by johnmhoran** [nexB/aboutcode-manager#123]
*  On Windows 10, `python build.py` throws an error:
```
Fri Jul 07, 2017 12:11 PM  /c/code/nexb/dev/aboutcode-manager JMH (16-python-build-script)
$ python build.py
=> BUILDING AboutCode App release: 2.0.0
Traceback (most recent call last):
  File "build.py", line 221, in <module>
    build()
  File "build.py", line 191, in build
    npm_bin = subprocess.check_output(['npm', 'bin'], stderr=subprocess.STDOUT).strip()
  File "C:\Python27\lib\subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

Fri Jul 07, 2017 12:12 PM  /c/code/nexb/dev/aboutcode-manager JMH (16-python-build-script)
$
```

*  This is the `npm bin` out on Windows 10:
```
Fri Jul 07, 2017 12:12 PM  /c/code/nexb/dev/aboutcode-manager JMH (16-python-build-script)
$ npm bin
C:\code\nexb\dev\aboutcode-manager\node_modules\.bin

Fri Jul 07, 2017 12:20 PM  /c/code/nexb/dev/aboutcode-manager JMH (16-python-build-script)
$
```

*  On Ubuntu 16.04, provided that a `dist` directory already exists (not yet tested on other platforms), `python build.py` runs without error and populates the `dist` directory with `AboutCode-Manager-linux-x64-2.0.0` and `AboutCode-Manager-linux-x64-2.0.0.tar.gz`.  Each contains an executable that launches the application.  However, the application does not function properly, e.g., no table is displayed on launch.

**Comment by jdaguil** [comment]
Closing since it is now working: https://github.com/nexB/aboutcode-manager/issues/16#issuecomment-314518105
